import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 3,
    borderBottomColor: "#A4161A",
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: "#A4161A",
  },
  headerSub: {
    fontSize: 8,
    color: "#666",
    marginTop: 2,
  },
  headerRight: {
    alignItems: "flex-end",
  },
  headerDate: {
    fontSize: 9,
    color: "#666",
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: "#A4161A",
    marginTop: 16,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#E5383B",
  },
  infoRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  infoLabel: {
    width: 120,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#444",
  },
  infoValue: {
    fontSize: 9,
    color: "#1a1a1a",
  },
  scopeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginBottom: 2,
  },
  scopeRowEven: {
    backgroundColor: "#f5f5f5",
  },
  scopeName: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
  },
  scopeStatus: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
  },
  conforme: { color: "#16a34a" },
  atencao: { color: "#ca8a04" },
  nao_conforme: { color: "#A4161A" },
  pendente: { color: "#999" },
  checklistItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
    paddingHorizontal: 12,
    fontSize: 8,
  },
  observation: {
    marginTop: 12,
    padding: 10,
    backgroundColor: "#f9f9f9",
    borderLeftWidth: 3,
    borderLeftColor: "#A4161A",
    fontSize: 9,
    lineHeight: 1.5,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#ddd",
    paddingTop: 8,
    fontSize: 7,
    color: "#999",
  },
  badge: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: "#fff",
    borderRadius: 2,
  },
  badgeAprovado: { backgroundColor: "#16a34a" },
  badgeReprovado: { backgroundColor: "#A4161A" },
});
